[cursor]
blink_interval = 750

[cursor.style]
blinking = "On"

[font]
builtin_box_drawing = true
size = 16.0

[font.bold]
family = "Anonymous Pro"
style = "Bold"

[font.bold_italic]
family = "Anonymous Pro"
style = "Bold Italic"

[font.italic]
family = "Anonymous Pro"
style = "Italic"

[font.normal]
family = "Anonymous Pro"

[[keyboard.bindings]]
action = "First"
key = "Key0"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "FirstOccupied"
key = "H"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "Last"
key = "Key4"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "Last"
key = "L"
mode = "Vi|~Search"
mods = "Shift"

[mouse]
hide_when_typing = true

[shell]
args = ["-c", "source ~/.zshrc && /usr/bin/tmux new"]
program = "/usr/bin/zsh"

[window.padding]
x = 8
y = 8
